spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///MyUploader?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.attackme.myuploader.model
upload:
  path: ./upload/